<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Firefighting Robot — Assembly + Orthogonal Sketches</title>
  <style>
    body{font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial;line-height:1.4;padding:18px;color:#111}
    h1,h2{margin:8px 0}
    .cols{display:flex;gap:18px;flex-wrap:wrap}
    .panel{flex:1 1 420px;background:#fff;border:1px solid #ddd;padding:12px;border-radius:8px}
    svg{width:100%;height:auto;border:1px solid #eee;background:#fbfbfb}
    code{background:#f4f4f4;padding:6px;border-radius:4px;display:block}
    ol li{margin:8px 0}
    .note{font-size:0.95em;color:#555}
  </style>
</head>
<body>
  <h1>Firefighting Robot — Step-by-step assembly + orthogonal sketches</h1>
  <p class="note">Assumptions: standard wooden popsicle stick = <strong>114 × 10 × 2 mm</strong>. All measurements are in <strong>mm</strong>. This document gives a practical, budget-friendly prototype build sized to use popsicle sticks and low-cost components.</p>  <h2>Quick specs (target)</h2>
  <ul>
    <li>Total height (approx): <strong>310 mm</strong> (legs 120 + torso 150 + head 40).</li>
    <li>Torso: <strong>100 mm</strong> wide × <strong>150 mm</strong> high × <strong>30 mm</strong> deep.</li>
    <li>Leg length: <strong>120 mm</strong> each (from hip to wheel axle).</li>
    <li>Wheel diameter: <strong>60 mm</strong>. Wheelbase (center-to-center): <strong>120 mm</strong>.</li>
    <li>Arm reach (shoulder to nozzle): <strong>120 mm</strong>.</li>
    <li>Reservoir: small plastic bottle ~<strong>200 mL</strong> (Ø 60 mm × 80 mm high).</li>
  </ul>  <h2>Parts (short)</h2>
  <ul>
    <li>Arduino Nano or Uno, motor driver (L298N), MOSFET (IRLZ44 or similar) for pump</li>
    <li>2 × DC gear motors (with wheels) — wheel Ø 60 mm</li>
    <li>2 × small caster wheels (Ø 25–30 mm) for balance</li>
    <li>2 × micro servos (SG90) for pan/tilt of nozzle</li>
    <li>3 × flame sensors, 1 × HC-SR04 ultrasonic</li>
    <li>1 × 3–6V small submersible pump (or inline 5V pump), tubing, nozzle</li>
    <li>Battery pack (7.4V or appropriate for motors) + 5V UBEC/regulator for servos/Arduino</li>
    <li>Popsicle sticks, hot glue, small plywood motor plates, small screws, zip ties</li>
  </ul>  <h2>Step-by-step assembly</h2>
  <ol>
    <li><strong>Prepare popsicle-stick panels</strong> — glue sticks side-by-side to make flat panels.
      <ul class="note"><li>Torso panel: 10 sticks wide → 100 mm width, glue 3 layers cross-grain for thickness ≈ 6 mm.</li>
      <li>Leg panels: make narrow panels 3 sticks (30 mm) wide; glue 4–5 sticks long to reach 120 mm.</li>
      </ul>
    </li><li><strong>Cut motor mount plates</strong> — small plywood rectangles 60 × 40 × 3 mm for gearmotor mounting. Drill holes to secure motor with small screws.</li>

<li><strong>Build the torso box</strong> — use two large panels (front/back) 150 × 100 mm and side strips 150 × 30 mm.
  <ul class="note"><li>Glue front and back panels to side strips to form a shallow box 100 × 150 × 30 mm. Inside add a small shelf (popsicle-stick strip) at 60 mm from bottom to hold motor driver and battery strap.</li></ul>
</li>

<li><strong>Assemble legs</strong> — for each leg create a rectangular column 120 × 30 × 30 mm made by folding/gluing panels around a 30 mm square core. Reinforce corners with extra sticks.
  <ul class="note"><li>At the bottom attach the plywood motor plate per leg so that the motor axle centers at the bottom center of the leg column.</li></ul>
</li>

<li><strong>Mount motors & wheels</strong> — fix gearmotors to motor plates; attach wheels (Ø60 mm). Check wheel axis height: with wheel fitted the axle should be ~8 mm below the leg bottom so wheel clears the frame.</li>

<li><strong>Attach caster(s)</strong> — add 2 small swivel casters under the front or center (choose front of robot as small bump-prevention). Place casters about 40 mm forward of wheel axle to prevent tipping.</li>

<li><strong>Mount torso to legs</strong> — glue or screw each leg to the inside bottom edge of the torso box. Leg centers spaced <strong>120 mm</strong> apart (center-to-center). Ensure the water tank can fit between legs inside the torso base area.</li>

<li><strong>Prepare arms</strong> — build two arm assemblies: shoulder link (30 × 20 × 10 mm) and forearm (~120 × 18 mm long). Cut small wooden brackets for servo mounts.
  <ul class="note"><li>Shoulder servo (pan) mounts to the top-front corner of torso; attach arm to servo horn.</li>
  <li>Wrist servo (tilt) mounts near arm end with a short bracket; nozzle attaches to wrist horn.</li></ul>
</li>

<li><strong>Install water reservoir & pump</strong> — place small bottle (Ø ~60 mm) low and centered in torso. Secure with zip ties or glue. Place pump either <em>inside</em> the reservoir (submersible) or inline between reservoir and arm tubing. Make sure pump outlet faces up into tubing.
  <ul class="note"><li>Route tubing from pump up through torso, into shoulder, through arm channel, to nozzle.</li></ul>
</li>

<li><strong>Mount electronics</strong> — attach Arduino Nano to the torso inner back wall, motor driver on shelf below Arduino, MOSFET & pump wiring nearby. Keep servos anchored to the 5V regulator. Keep battery strapped to lower shelf next to reservoir to keep COG low.</li>

<li><strong>Wire motors & servos</strong> — connect motors to motor driver, motor driver to battery; Arduino digital pins to driver inputs (with PWM). Connect servos to 5V regulated supply; route servo signal wires to Arduino pins. Connect flame sensors to analog inputs and HC-SR04 to digital pins.</li>

<li><strong>Mount sensors</strong> — glue or screw flame sensors across chest (left/center/right) at about <strong>shoulder height 200 mm from ground</strong>. Mount ultrasonic sensor centered above the three sensors near top of torso (about 220 mm high).</li>

<li><strong>Test electronics on bench</strong> — before final sealing: power up Arduino and sensors, verify motor direction, servo movement, flame sensor readings (log analog values), ultrasonic distance readings, pump switching via MOSFET (do dry run without water first or with pump out of reservoir).</li>

<li><strong>Final assembly & cable management</strong> — glue low-stress joints, use zip ties to route tubing & wires inside leg and torso channels; add small splash guard plate at front of electronics to minimize water exposure.</li>

<li><strong>Calibration & baseline tests</strong> — calibrate flame sensor thresholds (record analog values at 1m, 50 cm, 20 cm from small candle), set PWM for slow approach speeds, tune servo angles for aiming ±30°.
  <ul class="note"><li>Set conservative spray distance (sprayRange) at 30–50 cm depending on pump/nozzle capability.</li></ul>
</li>

<li><strong>Field test (controlled)</strong> — outdoors or with fire safety: test SEARCH → AIM → APPROACH → SPRAY cycles on a small candle. Keep a person with extinguisher nearby.</li>

  </ol>  <h2>Orthogonal sketches (front / back / side) — labeled</h2>
  <div class="cols">
    <div class="panel">
      <h3>Front view (scale illustration)</h3>
      <!-- Front SVG -->
      <svg viewBox="0 0 600 900" xmlns="http://www.w3.org/2000/svg">
        <!-- ground line -->
        <line x1="30" y1="820" x2="570" y2="820" stroke="#ccc" stroke-width="2"/><!-- head -->
    <rect x="250" y="50" width="100" height="40" rx="6" fill="#fff" stroke="#222"/>
    <text x="300" y="78" text-anchor="middle" font-size="12">Head (40 mm)</text>

    <!-- torso -->
    <rect x="200" y="100" width="200" height="300" rx="8" fill="#fff" stroke="#222"/>
    <text x="300" y="120" text-anchor="middle" font-size="12">Torso 100 × 150 mm (scaled)</text>

    <!-- flame sensors across chest -->
    <circle cx="240" cy="180" r="10" fill="#ffd" stroke="#222"/>
    <text x="240" y="200" font-size="10" text-anchor="middle">Flame L</text>
    <circle cx="300" cy="180" r="10" fill="#ffd" stroke="#222"/>
    <text x="300" y="200" font-size="10" text-anchor="middle">Flame C</text>
    <circle cx="360" cy="180" r="10" fill="#ffd" stroke="#222"/>
    <text x="360" y="200" font-size="10" text-anchor="middle">Flame R</text>

    <!-- ultrasonic sensor above -->
    <rect x="275" y="140" width="50" height="18" rx="4" fill="#eef" stroke="#222"/>
    <text x="300" y="154" text-anchor="middle" font-size="10">HC-SR04</text>

    <!-- arms -->
    <g id="arms">
      <!-- left arm -->
      <rect x="120" y="170" width="70" height="18" rx="6" fill="#fff" stroke="#222"/>
      <text x="155" y="188" font-size="10" text-anchor="middle">Arm (120 mm)</text>
      <!-- nozzle -->
      <circle cx="105" cy="179" r="8" fill="#9cf" stroke="#222"/>
      <text x="95" y="196" font-size="9">Nozzle</text>

      <!-- right arm -->
      <rect x="410" y="170" width="70" height="18" rx="6" fill="#fff" stroke="#222"/>
      <circle cx="495" cy="179" r="8" fill="#9cf" stroke="#222"/>
      <text x="495" y="196" font-size="9">Nozzle</text>
    </g>

    <!-- legs -->
    <rect x="220" y="410" width="40" height="220" rx="6" fill="#fff" stroke="#222"/>
    <rect x="340" y="410" width="40" height="220" rx="6" fill="#fff" stroke="#222"/>
    <text x="240" y="510" font-size="10">Leg L (120 mm)</text>
    <text x="380" y="510" font-size="10">Leg R (120 mm)</text>

    <!-- wheels -->
    <circle cx="240" cy="700" r="30" fill="#eee" stroke="#222"/>
    <text x="240" y="738" font-size="10" text-anchor="middle">Drive wheel Ø60</text>
    <circle cx="360" cy="700" r="30" fill="#eee" stroke="#222"/>
    <text x="360" y="738" font-size="10" text-anchor="middle">Drive wheel Ø60</text>

    <!-- caster in front -->
    <circle cx="300" cy="720" r="12" fill="#ddd" stroke="#222"/>
    <text x="300" y="742" font-size="10" text-anchor="middle">Caster Ø25</text>

    <!-- dimension arrows example -->
    <line x1="120" y1="80" x2="480" y2="80" stroke="#444" stroke-width="1.5" marker-end="url(#arr)" marker-start="url(#arr)"/>
    <text x="300" y="70" text-anchor="middle" font-size="11">Overall width (approx 160 mm)</text>

    <defs>
      <marker id="arr" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto">
        <path d="M0 0 L6 3 L0 6 z" fill="#444"/>
      </marker>
    </defs>
  </svg>
</div>

<div class="panel">
  <h3>Side view (scale illustration)</h3>
  <!-- Side SVG -->
  <svg viewBox="0 0 600 900" xmlns="http://www.w3.org/2000/svg">
    <line x1="30" y1="820" x2="570" y2="820" stroke="#ccc" stroke-width="2"/>

    <!-- profile: head -->
    <rect x="360" y="50" width="80" height="40" rx="6" fill="#fff" stroke="#222"/>
    <text x="400" y="78" text-anchor="middle" font-size="12">Head 40</text>

    <!-- torso depth -->
    <rect x="340" y="100" width="120" height="300" rx="8" fill="#fff" stroke="#222"/>
    <text x="400" y="120" text-anchor="middle" font-size="12">Torso depth 30 mm</text>

    <!-- reservoir inside torso (side) -->
    <rect x="375" y="260" width="50" height="80" rx="10" fill="#def" stroke="#222"/>
    <text x="400" y="355" font-size="10" text-anchor="middle">Reservoir (Ø60 × 80)</text>

    <!-- arm (side) -->
    <g>
      <rect x="280" y="170" width="100" height="16" rx="6" fill="#fff" stroke="#222"/>
      <circle cx="270" cy="178" r="8" fill="#9cf" stroke="#222"/>
      <text x="320" y="190" font-size="10">Arm 120 mm</text>
      <text x="270" y="196" font-size="9">Nozzle</text>
    </g>

    <!-- leg side column -->
    <rect x="360" y="410" width="36" height="220" rx="6" fill="#fff" stroke="#222"/>
    <circle cx="378" cy="700" r="30" fill="#eee" stroke="#222"/>
    <text x="420" y="720" font-size="10">Wheel Ø60</text>

    <!-- motor inside plate -->
    <rect x="360" y="640" width="36" height="16" fill="#ddd" stroke="#222"/>
    <text x="378" y="660" font-size="9" text-anchor="middle">Motor</text>

    <!-- electronics shelf and Arduino -->
    <rect x="365" y="200" width="28" height="18" fill="#f8f8f8" stroke="#222"/>
    <text x="400" y="208" font-size="9">Arduino</text>

    <!-- pump near reservoir -->
    <rect x="385" y="340" width="20" height="12" rx="3" fill="#fff" stroke="#222"/>
    <text x="400" y="360" font-size="9">Pump</text>

    <!-- dimension line for total height -->
    <line x1="300" y1="50" x2="300" y2="820" stroke="#444" stroke-width="1.2" marker-end="url(#arr)" marker-start="url(#arr)"/>
    <text x="260" y="440" font-size="11">Total height ~310 mm</text>

    <defs>
      <marker id="arr" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto">
        <path d="M0 0 L6 3 L0 6 z" fill="#444"/>
      </marker>
    </defs>
  </svg>
</div>

<div class="panel">
  <h3>Back view (scale illustration)</h3>
  <!-- Back SVG -->
  <svg viewBox="0 0 600 900" xmlns="http://www.w3.org/2000/svg">
    <line x1="30" y1="820" x2="570" y2="820" stroke="#ccc" stroke-width="2"/>

    <!-- torso back outline -->
    <rect x="200" y="100" width="200" height="300" rx="8" fill="#fff" stroke="#222"/>
    <text x="300" y="120" text-anchor="middle" font-size="12">Back: Torso 100×150</text>

    <!-- battery pack low and centered -->
    <rect x="260" y="320" width="80" height="60" rx="6" fill="#fee" stroke="#222"/>
    <text x="300" y="355" font-size="10">Battery pack</text>

    <!-- electronics (driver) -->
    <rect x="260" y="240" width="80" height="28" rx="4" fill="#f6f6f6" stroke="#222"/>
    <text x="300" y="258" font-size="9">Motor driver</text>

    <!-- water tank back view centered -->
    <circle cx="300" cy="200" r="30" fill="#def" stroke="#222"/>
    <text x="300" y="240" font-size="10" text-anchor="middle">Reservoir Ø60</text>

    <!-- ports for tubing -> arms -->
    <line x1="300" y1="170" x2="195" y2="180" stroke="#222" stroke-width="1"/>
    <line x1="300" y1="170" x2="405" y2="180" stroke="#222" stroke-width="1"/>
    <text x="150" y="180" font-size="9">Tubing -> Left arm</text>
    <text x="455" y="180" font-size="9">Tubing -> Right arm</text>

    <!-- legs and wheel back -->
    <rect x="220" y="410" width="40" height="220" rx="6" fill="#fff" stroke="#222"/>
    <rect x="340" y="410" width="40" height="220" rx="6" fill="#fff" stroke="#222"/>
    <circle cx="240" cy="700" r="30" fill="#eee" stroke="#222"/>
    <circle cx="360" cy="700" r="30" fill="#eee" stroke="#222"/>

  </svg>
</div>

  </div>  <h2>Notes & tips (final)</h2>
  <ul>
    <li>If you need more rigidity, add thin plywood braces inside the torso and at leg joints.</li>
    <li>Keep electronics elevated above the reservoir top and use waterproof tape on seams near tubing.</li>
    <li>If using a submersible pump, run the pump on a switched line with a MOSFET and a diode across the motor if required by the pump type.</li>
    <li>Adjust the arm length if your pump flow is weak — shorter arms mean better spray force at close range.</li>
  </ul>  <p class="note">If you want, I can export this page as a printable PDF or produce a higher-resolution technical drawing (SVG/DXF) with exact scaling for laser cutting small plywood brackets.</p>
</body>
</html>